# Generated by Django 5.2.9 on 2025-12-25 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('exception_type', models.CharField(choices=[('blocked', 'Blocked (No Appointments)'), ('modified', 'Modified Hours')], default='blocked', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exception Date',
                'verbose_name_plural': 'Exception Dates',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('allows_virtual', models.BooleanField(default=True)),
                ('allows_in_person', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Weekly Availability',
                'verbose_name_plural': 'Weekly Availabilities',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('modality', models.CharField(choices=[('virtual', 'Virtual'), ('in_person', 'In-Person'), ('phone', 'Phone Call')], default='virtual', max_length=20)),
                ('patient_type', models.CharField(choices=[('new', 'New Patient'), ('returning', 'Returning Patient'), ('discovery', 'Discovery Call')], default='new', max_length=20)),
                ('patient_details', models.JSONField(default=dict, help_text='Patient info: name, email, phone')),
                ('reason', models.TextField(blank=True, help_text='Reason for visit')),
                ('notes', models.TextField(blank=True, help_text='Internal notes (admin only)')),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('meeting_link', models.URLField(blank=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='services.service')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-scheduled_date', '-scheduled_time'],
                'indexes': [models.Index(fields=['scheduled_date', 'scheduled_time'], name='appointment_schedul_59e8bc_idx'), models.Index(fields=['status', 'scheduled_date'], name='appointment_status_93b56b_idx'), models.Index(fields=['reference_id'], name='appointment_referen_284f6f_idx')],
            },
        ),
    ]
