# Generated by Django 5.2.9 on 2025-12-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price_note',
            field=models.CharField(blank=True, help_text="e.g., 'Starting from' or 'Per session'", max_length=100),
        ),
    ]
