# Generated by Django 5.2.9 on 2025-12-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('appointment_created', 'Appointment Created'), ('appointment_approved', 'Appointment Approved'), ('appointment_rejected', 'Appointment Rejected'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_completed', 'Appointment Completed'), ('blog_published', 'Blog Post Published'), ('blog_updated', 'Blog Post Updated'), ('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('user_login', 'User Login'), ('user_logout', 'User Logout')], db_index=True, max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
